/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MovieBooking.view;

/**
 *
 * @author lenovo
 */
public class AuthenticationView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AuthenticationView.class.getName());

    /**
     * Creates new form AuthenticationView
     */
    public AuthenticationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LoginTextHeader4 = new javax.swing.JLabel();
        EmailTextField4 = new javax.swing.JTextField();
        EmailLabel4 = new javax.swing.JLabel();
        PasswordLabel4 = new javax.swing.JLabel();
        ForgotPasswordButton4 = new javax.swing.JToggleButton();
        PasswordPasswordField4 = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        SignUpButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        SingUpLabelHeader = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        EmailLabel5 = new javax.swing.JLabel();
        BackToLoginButton = new javax.swing.JToggleButton();
        EmailTextField5 = new javax.swing.JTextField();
        PasswordLabel5 = new javax.swing.JLabel();
        PasswordPasswordField5 = new javax.swing.JPasswordField();
        ConfirmPasswordField = new javax.swing.JLabel();
        ConfirmPasswordPasswordField = new javax.swing.JPasswordField();
        Signupbutton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        SingUpLabelHeader1 = new javax.swing.JLabel();
        EmailTextField6 = new javax.swing.JTextField();
        EmailLabel6 = new javax.swing.JLabel();
        BackToLoginButton1 = new javax.swing.JToggleButton();
        PasswordLabel6 = new javax.swing.JLabel();
        NewPasswordPasswordField = new javax.swing.JPasswordField();
        ConfirmPasswordField1 = new javax.swing.JLabel();
        ConfirmPasswordPasswordField1 = new javax.swing.JPasswordField();
        ResetPasswordButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MovieMint");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MovieBooking/adobe.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        LoginTextHeader4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginTextHeader4.setForeground(new java.awt.Color(0, 0, 0));
        LoginTextHeader4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginTextHeader4.setText("Login");

        EmailTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        EmailLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel4.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel4.setText("Email:");

        PasswordLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordLabel4.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel4.setText("Password:");

        ForgotPasswordButton4.setBackground(new java.awt.Color(255, 255, 255));
        ForgotPasswordButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ForgotPasswordButton4.setForeground(new java.awt.Color(0, 0, 0));
        ForgotPasswordButton4.setText("Forgot Password?");
        ForgotPasswordButton4.setBorder(null);
        ForgotPasswordButton4.setContentAreaFilled(false);
        ForgotPasswordButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForgotPasswordButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PasswordPasswordField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LoginButton.setBackground(new java.awt.Color(255, 153, 102));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        SignUpButton.setBackground(new java.awt.Color(255, 153, 102));
        SignUpButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignUpButton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpButton.setText("Sign Up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(LoginTextHeader4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ForgotPasswordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PasswordLabel4)
                        .addComponent(EmailTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(EmailLabel4)
                        .addComponent(PasswordPasswordField4)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(LoginTextHeader4)
                .addGap(34, 34, 34)
                .addComponent(EmailLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ForgotPasswordButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginButton)
                    .addComponent(SignUpButton))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );

        getContentPane().add(jPanel1, "card2");

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setForeground(new java.awt.Color(204, 255, 255));

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0)));
        jPanel9.setForeground(new java.awt.Color(102, 102, 102));

        SingUpLabelHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        SingUpLabelHeader.setForeground(new java.awt.Color(0, 0, 0));
        SingUpLabelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SingUpLabelHeader.setText("Sign Up");

        UsernameTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(0, 0, 0));
        UsernameLabel.setText("Username:");

        EmailLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel5.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel5.setText("Email:");

        BackToLoginButton.setBackground(new java.awt.Color(102, 102, 102));
        BackToLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackToLoginButton.setForeground(new java.awt.Color(0, 0, 0));
        BackToLoginButton.setText("Back To Login");
        BackToLoginButton.setBorder(null);
        BackToLoginButton.setContentAreaFilled(false);
        BackToLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        EmailTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        PasswordLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordLabel5.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel5.setText("Password:");

        PasswordPasswordField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        ConfirmPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfirmPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPasswordField.setText("Confirm Password: ");

        ConfirmPasswordPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        Signupbutton1.setBackground(new java.awt.Color(255, 153, 102));
        Signupbutton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Signupbutton1.setForeground(new java.awt.Color(255, 255, 255));
        Signupbutton1.setText("Sign Up");
        Signupbutton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Signupbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Signupbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(SingUpLabelHeader)
                .addGap(121, 121, 121))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Signupbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BackToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PasswordLabel5)
                                .addComponent(EmailLabel5)
                                .addComponent(UsernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(UsernameLabel)
                                .addComponent(EmailTextField5)
                                .addComponent(PasswordPasswordField5)
                                .addComponent(ConfirmPasswordField)
                                .addComponent(ConfirmPasswordPasswordField)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(SingUpLabelHeader)
                .addGap(34, 34, 34)
                .addComponent(UsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmailLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordPasswordField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmPasswordField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BackToLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Signupbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, "card3");

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, new java.awt.Color(0, 0, 0)));
        jPanel10.setForeground(new java.awt.Color(102, 102, 102));

        SingUpLabelHeader1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        SingUpLabelHeader1.setForeground(new java.awt.Color(0, 0, 0));
        SingUpLabelHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SingUpLabelHeader1.setText("Rest Password");

        EmailTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        EmailTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextField6ActionPerformed(evt);
            }
        });

        EmailLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmailLabel6.setForeground(new java.awt.Color(0, 0, 0));
        EmailLabel6.setText("Email:");

        BackToLoginButton1.setBackground(new java.awt.Color(102, 102, 102));
        BackToLoginButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BackToLoginButton1.setForeground(new java.awt.Color(0, 0, 0));
        BackToLoginButton1.setText("Back To Login");
        BackToLoginButton1.setBorder(null);
        BackToLoginButton1.setContentAreaFilled(false);
        BackToLoginButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        PasswordLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PasswordLabel6.setForeground(new java.awt.Color(0, 0, 0));
        PasswordLabel6.setText("New Password:");

        NewPasswordPasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        ConfirmPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ConfirmPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPasswordField1.setText("Confirm Password: ");

        ConfirmPasswordPasswordField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        ResetPasswordButton.setBackground(new java.awt.Color(255, 153, 102));
        ResetPasswordButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResetPasswordButton.setForeground(new java.awt.Color(255, 255, 255));
        ResetPasswordButton.setText("Reset Password");
        ResetPasswordButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ResetPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ResetPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackToLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EmailTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(EmailLabel6)
                        .addComponent(NewPasswordPasswordField)
                        .addComponent(ConfirmPasswordField1)
                        .addComponent(ConfirmPasswordPasswordField1)
                        .addComponent(PasswordLabel6))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(SingUpLabelHeader1)
                        .addGap(18, 18, 18)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(SingUpLabelHeader1)
                .addGap(27, 27, 27)
                .addComponent(EmailLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewPasswordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmPasswordField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPasswordPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(BackToLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResetPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        getContentPane().add(jPanel8, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Signupbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Signupbutton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Signupbutton1ActionPerformed

    private void EmailTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextField6ActionPerformed

    private void ResetPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPasswordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetPasswordButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AuthenticationView().setVisible(true));
    }
    
    // Getter methods for controller access
    // Login card getters
    public javax.swing.JTextField getEmailTextField4() {
        return EmailTextField4;
    }
    
    public javax.swing.JPasswordField getPasswordPasswordField4() {
        return PasswordPasswordField4;
    }
    
    public javax.swing.JButton getLoginButton4() {
        return LoginButton;
    }
    
    public javax.swing.JButton getSignUpButton4() {
        return SignUpButton;
    }
    
    public javax.swing.JToggleButton getForgotPasswordButton4() {
        return ForgotPasswordButton4;
    }
    
    // SignUp card getters
    public javax.swing.JTextField getUsernameTextField() {
        return UsernameTextField;
    }
    
    public javax.swing.JTextField getEmailTextField5() {
        return EmailTextField5;
    }
    
    public javax.swing.JPasswordField getPasswordPasswordField5() {
        return PasswordPasswordField5;
    }
    
    public javax.swing.JPasswordField getConfirmPasswordPasswordField() {
        return ConfirmPasswordPasswordField;
    }
    
    public javax.swing.JButton getSignupbutton1() {
        return Signupbutton1;
    }
    
    public javax.swing.JToggleButton getBackToLoginButton() {
        return BackToLoginButton;
    }
    
    // Forgot password card getters
    public javax.swing.JTextField getEmailTextField6() {
        return EmailTextField6;
    }
    
    public javax.swing.JPasswordField getNewPasswordPasswordField() {
        return NewPasswordPasswordField;
    }
    
    public javax.swing.JPasswordField getConfirmPasswordPasswordField1() {
        return ConfirmPasswordPasswordField1;
    }
    
    public javax.swing.JButton getResetPasswordButton() {
        return ResetPasswordButton;
    }
    
    public javax.swing.JToggleButton getBackToLoginButton1() {
        return BackToLoginButton1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BackToLoginButton;
    private javax.swing.JToggleButton BackToLoginButton1;
    private javax.swing.JLabel ConfirmPasswordField;
    private javax.swing.JLabel ConfirmPasswordField1;
    private javax.swing.JPasswordField ConfirmPasswordPasswordField;
    private javax.swing.JPasswordField ConfirmPasswordPasswordField1;
    private javax.swing.JLabel EmailLabel4;
    private javax.swing.JLabel EmailLabel5;
    private javax.swing.JLabel EmailLabel6;
    private javax.swing.JTextField EmailTextField4;
    private javax.swing.JTextField EmailTextField5;
    private javax.swing.JTextField EmailTextField6;
    private javax.swing.JToggleButton ForgotPasswordButton4;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginTextHeader4;
    private javax.swing.JPasswordField NewPasswordPasswordField;
    private javax.swing.JLabel PasswordLabel4;
    private javax.swing.JLabel PasswordLabel5;
    private javax.swing.JLabel PasswordLabel6;
    private javax.swing.JPasswordField PasswordPasswordField4;
    private javax.swing.JPasswordField PasswordPasswordField5;
    private javax.swing.JButton ResetPasswordButton;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JButton Signupbutton1;
    private javax.swing.JLabel SingUpLabelHeader;
    private javax.swing.JLabel SingUpLabelHeader1;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
