/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MovieBooking.view;

/**
 *
 * @author lenovo
 */
public class MovieBookingView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MovieBookingView.class.getName());

    /**
     * Creates new form MovieBookingView
     */
    public MovieBookingView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AdminPannel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        MoviesButton = new javax.swing.JButton();
        UsersButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        Users = new javax.swing.JPanel();
        Movies = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        UpdateButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        UserpPannel = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MovieBooking/moviemint.png"))); // NOI18N

        HomeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(0, 0, 0));
        HomeButton.setText("Home");
        HomeButton.setBorder(null);
        HomeButton.setContentAreaFilled(false);
        HomeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeButtonMouseExited(evt);
            }
        });

        MoviesButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MoviesButton.setForeground(new java.awt.Color(0, 0, 0));
        MoviesButton.setText("Movies");
        MoviesButton.setBorder(null);
        MoviesButton.setContentAreaFilled(false);
        MoviesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        UsersButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsersButton.setForeground(new java.awt.Color(0, 0, 0));
        UsersButton.setText("Users");
        UsersButton.setBorder(null);
        UsersButton.setContentAreaFilled(false);
        UsersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jButton5.setBackground(new java.awt.Color(255, 153, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LogOut");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jPanel1.add(Home, "card2");

        javax.swing.GroupLayout UsersLayout = new javax.swing.GroupLayout(Users);
        Users.setLayout(UsersLayout);
        UsersLayout.setHorizontalGroup(
            UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        UsersLayout.setVerticalGroup(
            UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jPanel1.add(Users, "card4");

        Movies.setBackground(new java.awt.Color(241, 229, 237));

        jTable2.setBackground(new java.awt.Color(204, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Director", "Genre", "Language ", "Time", "Rated"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        UpdateButton.setBackground(new java.awt.Color(255, 153, 102));
        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("UPDATE");
        UpdateButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AddButton.setBackground(new java.awt.Color(255, 153, 102));
        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("ADD");
        AddButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        DeleteButton.setBackground(new java.awt.Color(255, 153, 102));
        DeleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteButton.setText("Delete");
        DeleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout MoviesLayout = new javax.swing.GroupLayout(Movies);
        Movies.setLayout(MoviesLayout);
        MoviesLayout.setHorizontalGroup(
            MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoviesLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 145, Short.MAX_VALUE))
            .addGroup(MoviesLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        MoviesLayout.setVerticalGroup(
            MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MoviesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MoviesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(HomeButton)
                .addGap(68, 68, 68)
                .addComponent(MoviesButton)
                .addGap(68, 68, 68)
                .addComponent(UsersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(Movies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MoviesButton)
                            .addComponent(HomeButton)
                            .addComponent(UsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Movies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout AdminPannelLayout = new javax.swing.GroupLayout(AdminPannel);
        AdminPannel.setLayout(AdminPannelLayout);
        AdminPannelLayout.setHorizontalGroup(
            AdminPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPannelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AdminPannelLayout.setVerticalGroup(
            AdminPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPannelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        getContentPane().add(AdminPannel, "card2");

        javax.swing.GroupLayout UserpPannelLayout = new javax.swing.GroupLayout(UserpPannel);
        UserpPannel.setLayout(UserpPannelLayout);
        UserpPannelLayout.setHorizontalGroup(
            UserpPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );
        UserpPannelLayout.setVerticalGroup(
            UserpPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        getContentPane().add(UserpPannel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseExited
        if (!isCurrentPage("home")) {
            HomeButton.setText("Home");
        }
    }//GEN-LAST:event_HomeButtonMouseExited

    private void HomeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseEntered
        if (!HomeButton.getText().contains("underline")) {
            HomeButton.setText("<html><span style='text-decoration: underline; text-decoration-thickness: 2px;'>Home</span></html>");
        }
    }//GEN-LAST:event_HomeButtonMouseEntered
    
    /**
     * Helper method to check if a page is currently active
     * @param page The page name to check ("home", "movies", "users")
     * @return true if the specified page is currently active
     */
    private boolean isCurrentPage(String page) {
        // Check if this is the current active page by checking controller state
        return (page.equals("home") && HomeButton.getText().contains("underline") && !MoviesButton.getText().contains("underline") && !UsersButton.getText().contains("underline")) ||
               (page.equals("movies") && MoviesButton.getText().contains("underline") && !HomeButton.getText().contains("underline") && !UsersButton.getText().contains("underline")) ||
               (page.equals("users") && UsersButton.getText().contains("underline") && !HomeButton.getText().contains("underline") && !MoviesButton.getText().contains("underline"));
    }
    
    // Movies button mouse hover handlers
    private void MoviesButtonMouseEntered(java.awt.event.MouseEvent evt) {
        // Add underline effect on hover if not already underlined
        if (!MoviesButton.getText().contains("underline")) {
            MoviesButton.setText("<html><span style='text-decoration: underline; text-decoration-thickness: 2px;'>Movies</span></html>");
        }
    }
    
    private void MoviesButtonMouseExited(java.awt.event.MouseEvent evt) {
        // Remove underline effect only if not the current active page
        if (!isCurrentPage("movies")) {
            MoviesButton.setText("Movies");
        }
    }
    
    // Users button mouse hover handlers
    private void UsersButtonMouseEntered(java.awt.event.MouseEvent evt) {
        // Add underline effect on hover if not already underlined
        if (!UsersButton.getText().contains("underline")) {
            UsersButton.setText("<html><span style='text-decoration: underline; text-decoration-thickness: 2px;'>Users</span></html>");
        }
    }
    
    private void UsersButtonMouseExited(java.awt.event.MouseEvent evt) {
        // Remove underline effect only if not the current active page
        if (!isCurrentPage("users")) {
            UsersButton.setText("Users");
        }
    }

    // Action handler methods for buttons
    private void MoviesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by controller
    }

    private void UsersButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by controller
    }

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by controller
    }

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by controller
    }

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by controller
    }

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Handled by controller
    }

    /**
     * @param args the command line arguments
     */
    
    // Getter methods for controller access
    public javax.swing.JButton getHomeButton() {
        return HomeButton;
    }
    
    public javax.swing.JButton getMoviesButton() {
        return MoviesButton;
    }
    
    public javax.swing.JButton getUsersButton() {
        return UsersButton;
    }
    
    public javax.swing.JButton getLogoutButton() {
        return jButton5;
    }
    
    public javax.swing.JPanel getContentPanel() {
        return jPanel1;
    }
    
    public javax.swing.JTable getMovieTable() {
        return jTable2;
    }
    
    public javax.swing.JButton getAddButton() {
        return AddButton;
    }
    
    public javax.swing.JButton getUpdateButton() {
        return UpdateButton;
    }
    
    public javax.swing.JButton getDeleteButton() {
        return DeleteButton;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JPanel AdminPannel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JPanel Home;
    private javax.swing.JButton HomeButton;
    private javax.swing.JPanel Movies;
    private javax.swing.JButton MoviesButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel UserpPannel;
    private javax.swing.JPanel Users;
    private javax.swing.JButton UsersButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
